export const recipes = [
  {
    slug: "creamy-tuscan-chicken-orzo",
    title: "Creamy Tuscan Chicken Orzo",
    category: "Dinner",
    time: 30,
    servings: 4,
    difficulty: "Easy",
    tag: "Reader favorite",
    image:
"https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?auto=format&fit=crop&w=1200&q=85",
    
    description:
      "A cozy one-pan dinner with tender chicken, sun-dried tomatoes, spinach, and a silky Parmesan sauce.",
    keywords: [
      "easy weeknight dinner",
      "one pan chicken orzo",
      "creamy chicken dinner",
    ],
    ingredients: [
      "1 lb boneless, skinless chicken breast, cut into bite-size pieces",
      "1 tbsp olive oil",
      "3 cloves garlic, minced",
      "1 cup dry orzo",
      "⅓ cup chopped sun-dried tomatoes",
      "3 cups low-sodium chicken broth",
      "½ cup heavy cream",
      "2 cups baby spinach",
      "½ cup finely grated Parmesan",
      "½ tsp Italian seasoning",
      "Salt and black pepper, to taste",
    ],
    steps: [
      "Pat the chicken dry and season with Italian seasoning, salt, and pepper.",
      "Heat olive oil in a large deep skillet over medium-high heat. Cook chicken for 4–5 minutes until lightly golden; transfer to a plate.",
      "Add garlic and sun-dried tomatoes. Stir for 30 seconds, then add orzo and broth. Scrape up any browned bits.",
      "Bring to a gentle simmer, cover, and cook for 8–10 minutes, stirring once or twice, until the orzo is nearly tender.",
      "Stir in cream, spinach, Parmesan, and chicken. Simmer for 2–3 minutes until the chicken is cooked through and the sauce is creamy.",
      "Taste, adjust seasoning, and serve warm with extra Parmesan.",
    ],
    tips: "Keep the pan at a gentle simmer so the orzo cooks evenly. Add a splash of broth if the sauce thickens before the pasta is tender.",
    season: "Fall favorite",
  },
  {
    slug: "sheet-pan-maple-chicken-sweet-potatoes",
    title: "Sheet-Pan Maple Chicken & Sweet Potatoes",
    category: "Dinner",
    time: 35,
    servings: 4,
    difficulty: "Easy",
    tag: "Fall favorite",
    image:
      "https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=1200&q=85",
    description:
      "A low-fuss fall dinner with savory chicken, caramelized sweet potatoes, and a maple-Dijon glaze.",
    keywords: [
      "sheet pan chicken dinner",
      "fall dinner ideas",
      "maple chicken sweet potatoes",
    ],
    ingredients: [
      "4 small boneless chicken thighs",
      "2 medium sweet potatoes, cubed",
      "1 red onion, cut into wedges",
      "2 tbsp olive oil",
      "1½ tbsp pure maple syrup",
      "1 tbsp Dijon mustard",
      "1 tsp smoked paprika",
      "½ tsp garlic powder",
      "Salt and black pepper",
      "Fresh parsley, to finish",
    ],
    steps: [
      "Heat oven to 425°F (220°C). Line a large rimmed sheet pan with parchment.",
      "Whisk olive oil, maple syrup, Dijon, paprika, garlic powder, salt, and pepper in a small bowl.",
      "Toss sweet potatoes and onion with half the glaze and spread across the pan. Roast for 10 minutes.",
      "Add chicken to the pan and brush with the remaining glaze.",
      "Roast for another 18–22 minutes, until the vegetables are tender and the thickest part of the chicken reaches 165°F (74°C).",
      "Rest for 5 minutes, sprinkle with parsley, and serve.",
    ],
    tips: "Cut the sweet potatoes into similar-size cubes so they roast evenly. Use a food thermometer to check chicken doneness.",
    season: "October pick",
  },
  {
    slug: "easy-chicken-noodle-soup",
    title: "Easy Homemade Chicken Noodle Soup",
    category: "Soups",
    time: 40,
    servings: 6,
    difficulty: "Easy",
    tag: "Comfort food",
    image:
      "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=85",
    description:
      "A soothing bowl of chicken noodle soup with tender vegetables, herbs, and a flavorful broth.",
    keywords: [
      "easy chicken noodle soup",
      "homemade soup recipe",
      "cozy fall soup",
    ],
    ingredients: [
      "1 tbsp olive oil",
      "1 medium yellow onion, diced",
      "3 carrots, sliced",
      "2 celery stalks, sliced",
      "2 cloves garlic, minced",
      "8 cups low-sodium chicken broth",
      "2 cups cooked shredded chicken",
      "2 cups egg noodles",
      "1 tsp dried thyme",
      "1 bay leaf",
      "Salt and black pepper",
      "2 tbsp chopped parsley",
    ],
    steps: [
      "Warm olive oil in a large pot over medium heat. Add onion, carrots, and celery; cook for 5–6 minutes.",
      "Stir in garlic and thyme for 30 seconds. Add broth and bay leaf.",
      "Bring to a boil, then reduce heat and simmer for 15 minutes until vegetables soften.",
      "Add noodles and cook according to package directions.",
      "Stir in cooked chicken and simmer until hot. Remove bay leaf, season to taste, and add parsley.",
      "Serve immediately. If storing leftovers, keep noodles separate when possible so they do not soak up too much broth.",
    ],
    tips: "Rotisserie chicken makes this a fast weeknight option. Add a little extra broth when reheating leftovers.",
    season: "Cozy classic",
  },
  {
    slug: "apple-cinnamon-baked-oatmeal",
    title: "Apple Cinnamon Baked Oatmeal",
    category: "Breakfast",
    time: 40,
    servings: 6,
    difficulty: "Easy",
    tag: "Make-ahead breakfast",
    image:
      "https://images.unsplash.com/photo-1517673132405-a56a62b18caf?auto=format&fit=crop&w=1200&q=85",
    description:
      "Warm baked oats with crisp apple pieces, cinnamon, and a lightly sweet finish—perfect for breakfast prep.",
    keywords: [
      "apple cinnamon baked oatmeal",
      "easy make ahead breakfast",
      "healthy fall breakfast",
    ],
    ingredients: [
      "2 cups old-fashioned rolled oats",
      "1 tsp baking powder",
      "1½ tsp ground cinnamon",
      "¼ tsp salt",
      "1½ cups milk of choice",
      "1 large egg",
      "⅓ cup maple syrup",
      "2 tbsp melted butter or neutral oil",
      "1 tsp vanilla extract",
      "1 large apple, diced",
      "¼ cup chopped walnuts (optional)",
    ],
    steps: [
      "Heat oven to 350°F (175°C). Lightly grease an 8-inch square baking dish.",
      "Mix oats, baking powder, cinnamon, and salt in a large bowl.",
      "In another bowl, whisk milk, egg, maple syrup, melted butter, and vanilla.",
      "Pour wet ingredients into dry ingredients and stir in the diced apple.",
      "Transfer to the dish, scatter walnuts on top if using, and bake for 30–35 minutes until set and golden at the edges.",
      "Cool for 5–10 minutes. Serve warm with yogurt or a splash of milk.",
    ],
    tips: "Refrigerate portions in an airtight container for up to four days. Reheat with a splash of milk to keep the oats soft.",
    season: "Fall breakfast",
  },
  {
    slug: "crispy-black-bean-tacos",
    title: "Crispy Black Bean Tacos",
    category: "Vegetarian",
    time: 20,
    servings: 4,
    difficulty: "Easy",
    tag: "Budget friendly",
    image:
      "https://images.unsplash.com/photo-1551509265-0e4f3a4b4c7b?auto=format&fit=crop&w=1200&q=85",
    description:
      "Crunchy skillet tacos filled with seasoned black beans, melty cheese, and fresh toppings.",
    keywords: [
      "easy vegetarian tacos",
      "black bean taco recipe",
      "budget friendly dinner",
    ],
    ingredients: [
      "1 can (15 oz) black beans, drained and rinsed",
      "1 tsp olive oil",
      "½ tsp ground cumin",
      "½ tsp smoked paprika",
      "8 small corn tortillas",
      "1 cup shredded Monterey Jack or cheddar",
      "1 avocado, sliced",
      "1 cup shredded lettuce",
      "Salsa and lime wedges",
      "Salt, to taste",
    ],
    steps: [
      "Gently mash about one-third of the black beans with a fork.",
      "Heat oil in a skillet over medium heat. Add beans, cumin, paprika, and a pinch of salt; cook for 3 minutes.",
      "Warm tortillas briefly so they bend without cracking. Add beans and a sprinkle of cheese to one half of each tortilla.",
      "Fold and cook in a lightly oiled skillet for 2–3 minutes per side until crisp and the cheese melts.",
      "Serve with avocado, lettuce, salsa, and lime wedges.",
    ],
    tips: "Do not overfill the tortillas. Keep cooked tacos warm on a rack in a low oven while you finish the batch.",
    season: "Anytime favorite",
  },
  {
    slug: "one-pot-tomato-basil-pasta",
    title: "One-Pot Tomato Basil Pasta",
    category: "Dinner",
    time: 25,
    servings: 4,
    difficulty: "Easy",
    tag: "One-pot wonder",
    image:
      "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=1200&q=85",
    description:
      "A simple weeknight pasta cooked in one pot with juicy tomatoes, garlic, basil, and Parmesan.",
    keywords: [
      "one pot pasta recipe",
      "easy tomato basil pasta",
      "quick weeknight dinner",
    ],
    ingredients: [
      "12 oz linguine or spaghetti",
      "1 pint cherry tomatoes, halved",
      "4 cloves garlic, thinly sliced",
      "4½ cups vegetable broth or water",
      "2 tbsp olive oil",
      "½ tsp red pepper flakes (optional)",
      "½ tsp salt, plus more to taste",
      "½ cup grated Parmesan",
      "½ cup fresh basil leaves",
      "Black pepper",
    ],
    steps: [
      "Place pasta, tomatoes, garlic, broth, olive oil, red pepper flakes, and salt in a wide pot.",
      "Bring to a boil, then reduce to a lively simmer. Cook uncovered for 9–12 minutes, stirring often so pasta does not stick.",
      "When pasta is al dente and most liquid has reduced to a glossy sauce, turn off the heat. Add a splash of water if needed.",
      "Fold in Parmesan and basil. Season with black pepper and more salt to taste.",
      "Serve straight from the pot with extra basil and Parmesan.",
    ],
    tips: "Use a wide pot so the pasta can lie mostly flat. Different pasta shapes may need a little more liquid or cooking time.",
    season: "Weeknight staple",
  },
  {
    slug: "pumpkin-spice-pancakes",
    title: "Fluffy Pumpkin Spice Pancakes",
    category: "Breakfast",
    time: 20,
    servings: 4,
    difficulty: "Easy",
    tag: "Seasonal",
    image:
      "https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=1200&q=85",
    description:
      "Soft pumpkin pancakes with warm spices for a relaxed fall breakfast or weekend brunch.",
    keywords: [
      "pumpkin spice pancakes",
      "fall breakfast ideas",
      "easy pumpkin recipes",
    ],
    ingredients: [
      "1½ cups all-purpose flour",
      "2 tbsp brown sugar",
      "2 tsp baking powder",
      "1 tsp pumpkin pie spice",
      "¼ tsp salt",
      "¾ cup milk",
      "½ cup pumpkin purée",
      "1 large egg",
      "2 tbsp melted butter",
      "1 tsp vanilla extract",
      "Maple syrup, to serve",
    ],
    steps: [
      "Whisk flour, brown sugar, baking powder, pumpkin pie spice, and salt in a bowl.",
      "In another bowl, whisk milk, pumpkin purée, egg, melted butter, and vanilla until smooth.",
      "Fold wet ingredients into dry ingredients just until combined; a few small lumps are fine.",
      "Heat a lightly greased skillet over medium heat. Pour about ¼ cup batter per pancake.",
      "Cook until bubbles form and edges look set, about 2 minutes. Flip and cook 1–2 minutes more.",
      "Serve warm with maple syrup and your favorite toppings.",
    ],
    tips: "Avoid overmixing for tender pancakes. If the batter seems too thick, add milk one tablespoon at a time.",
    season: "Fall brunch",
  },
];
export const categories = [
  {
    slug: "dinner",
    name: "Easy Dinners",
    desc: "Reliable weeknight dinners with simple ingredients.",
    image:
      "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=85",
  },
  {
    slug: "breakfast",
    name: "Breakfast",
    desc: "Make-ahead breakfasts and slow weekend favorites.",
    image:
      "https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=1000&q=85",
  },
  {
    slug: "soups",
    name: "Soups & Stews",
    desc: "Comforting bowls for chilly days and busy nights.",
    image:
      "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=85",
  },
  {
    slug: "vegetarian",
    name: "Vegetarian",
    desc: "Colorful, satisfying meat-free meals for any day.",
    image:
      "https://images.unsplash.com/photo-1551509265-0e4f3a4b4c7b?auto=format&fit=crop&w=1000&q=85",
  },
];
export function findRecipe(slug) {
  return recipes.find((r) => r.slug === slug);
}
