function img(id) {
  return `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=85`;
}

export const recipes = [
  {
    slug: "creamy-tuscan-chicken-orzo",
    title: "Creamy Tuscan Chicken Orzo",
    category: "Dinner",
    prepMinutes: 10,
    cookMinutes: 20,
    time: 30,
    servings: 4,
    difficulty: "Easy",
    tag: "Reader favorite",
    image: img("photo-1598103442097-8b74394b95c6"),
    imageAlt: "A whole roasted chicken in a cast-iron skillet",
    description:
      "A one-pan dinner of chicken, orzo, sun-dried tomatoes, spinach, and a Parmesan cream sauce.",
    intro:
      "This skillet dinner cooks the orzo in the same pan as the chicken, so the pasta picks up the browned bits. It is a 30-minute meal if the chicken is already cut and the spinach is washed.",
    keywords: ["easy chicken orzo recipe", "30 minute chicken dinner", "creamy tuscan chicken"],
    ingredients: [
      "1 lb boneless, skinless chicken breast, cut into bite-size pieces",
      "1 tbsp olive oil",
      "3 cloves garlic, minced",
      "1 cup dry orzo",
      "1/3 cup chopped sun-dried tomatoes",
      "3 cups low-sodium chicken broth",
      "1/2 cup heavy cream",
      "2 cups baby spinach",
      "1/2 cup finely grated Parmesan",
      "1/2 tsp Italian seasoning",
      "Salt and black pepper, to taste",
    ],
    steps: [
      "Pat the chicken dry and season with Italian seasoning, salt, and pepper.",
      "Heat the olive oil in a large deep skillet over medium-high heat. Cook the chicken for 4 to 5 minutes, until lightly golden, then transfer it to a plate. It will finish cooking in the sauce.",
      "Add the garlic and sun-dried tomatoes. Stir for 30 seconds, then add the orzo and broth. Scrape up the browned bits.",
      "Bring to a gentle simmer, cover, and cook for 8 to 10 minutes, stirring once or twice, until the orzo is nearly tender.",
      "Stir in the cream, spinach, Parmesan, and chicken. Simmer 2 to 3 minutes, until the thickest piece of chicken reaches 165°F (74°C) and the sauce looks creamy.",
      "Taste, adjust the salt, and serve warm with extra Parmesan.",
    ],
    tips: "Keep the simmer gentle so the orzo cooks evenly. Add a splash of broth if the sauce thickens before the pasta is tender.",
    storage:
      "Refrigerate in a shallow container within two hours. It keeps for 3 days. The orzo will drink some sauce, so loosen leftovers with a splash of broth while reheating to 165°F (74°C).",
    substitutions: [
      "Chicken thighs can replace the breast. Cook them to the same 165°F (74°C).",
      "Half-and-half can replace the heavy cream if you avoid a hard boil.",
      "Chopped kale can replace the spinach. Add it 2 minutes earlier.",
    ],
    season: "Fall favorite",
  },
  {
    slug: "sheet-pan-maple-chicken-sweet-potatoes",
    title: "Sheet-Pan Maple Chicken and Sweet Potatoes",
    category: "Dinner",
    prepMinutes: 15,
    cookMinutes: 30,
    time: 45,
    servings: 4,
    difficulty: "Easy",
    tag: "Fall favorite",
    image: img("photo-1532550907401-a500c9a57435"),
    imageAlt: "Roasted chicken on a platter with herbs",
    description:
      "Chicken thighs and sweet potatoes roast on one pan under a maple-Dijon glaze.",
    intro:
      "The sweet potatoes start alone so they soften before the chicken goes on the pan. A short glaze of maple, mustard, and smoked paprika browns in a hot oven without a lot of hands-on time.",
    keywords: ["sheet pan chicken and sweet potatoes", "easy sheet pan dinner", "30 minute chicken dinner"],
    ingredients: [
      "4 small boneless chicken thighs",
      "2 medium sweet potatoes, cut into 3/4-inch cubes",
      "1 red onion, cut into wedges",
      "2 tbsp olive oil",
      "1 1/2 tbsp pure maple syrup",
      "1 tbsp Dijon mustard",
      "1 tsp smoked paprika",
      "1/2 tsp garlic powder",
      "Salt and black pepper",
      "Fresh parsley, to finish",
    ],
    steps: [
      "Heat the oven to 425°F (220°C). Line a large rimmed sheet pan with parchment.",
      "Whisk the olive oil, maple syrup, Dijon, paprika, garlic powder, salt, and pepper.",
      "Toss the sweet potatoes and onion with half the glaze. Spread them on the pan and roast for 10 minutes.",
      "Add the chicken, brush it with the remaining glaze, and roast 18 to 22 minutes more.",
      "The vegetables should be tender and the thickest part of the chicken should read 165°F (74°C).",
      "Rest for 5 minutes, sprinkle with parsley, and serve.",
    ],
    tips: "Cut the sweet potatoes to a similar size so they finish together. Use a thermometer for the chicken.",
    storage:
      "Refrigerate within two hours and eat within 3 to 4 days. Reheat covered at 350°F (175°C) until the chicken reaches 165°F (74°C).",
    substitutions: [
      "Butternut squash cubes can replace the sweet potato. Check them early. They often soften faster.",
      "Bone-in thighs need more time. Start checking at 30 minutes and cook to 165°F (74°C).",
      "Honey can replace the maple syrup in the same amount.",
    ],
    season: "October pick",
  },
  {
    slug: "easy-chicken-noodle-soup",
    title: "Easy Homemade Chicken Noodle Soup",
    category: "Soups",
    prepMinutes: 15,
    cookMinutes: 25,
    time: 40,
    servings: 6,
    difficulty: "Easy",
    tag: "Comfort food",
    image: img("photo-1547592180-85f173990554"),
    imageAlt: "A bowl of chicken noodle soup with carrots, noodles, and herbs",
    description:
      "A pot of chicken noodle soup with carrots, celery, egg noodles, and shredded cooked chicken.",
    intro:
      "Using cooked chicken keeps this soup on a weeknight clock. The vegetables simmer until just tender, then the noodles go in so they do not turn to mush if you save leftovers.",
    keywords: ["easy chicken noodle soup recipe", "homemade chicken noodle soup", "quick chicken soup"],
    ingredients: [
      "1 tbsp olive oil",
      "1 medium yellow onion, diced",
      "3 carrots, sliced",
      "2 celery stalks, sliced",
      "2 cloves garlic, minced",
      "8 cups low-sodium chicken broth",
      "2 cups cooked shredded chicken",
      "2 cups egg noodles",
      "1 tsp dried thyme",
      "1 bay leaf",
      "Salt and black pepper",
      "2 tbsp chopped parsley",
    ],
    steps: [
      "Warm the oil in a large pot over medium heat. Cook the onion, carrots, and celery for 5 to 6 minutes.",
      "Stir in the garlic and thyme for 30 seconds. Add the broth and bay leaf.",
      "Bring to a boil, then simmer for 15 minutes, until the carrots are tender.",
      "Add the noodles and cook for the time on the package.",
      "Stir in the chicken and heat until the soup is steaming and the chicken reaches 165°F (74°C).",
      "Remove the bay leaf, season to taste, and add the parsley.",
    ],
    tips: "Store the noodles separately when you can, so they do not absorb all of the broth.",
    storage:
      "Refrigerate within two hours for up to 4 days. Reheat to 165°F (74°C) and add broth if the noodles have thickened the soup.",
    substitutions: [
      "Rotisserie chicken works if you remove the skin and shred the meat.",
      "Vegetable broth can replace chicken broth. The soup will taste lighter.",
      "Small pasta can replace egg noodles. Cook it only until al dente.",
    ],
    season: "Cozy classic",
  },
  {
    slug: "apple-cinnamon-baked-oatmeal",
    title: "Apple Cinnamon Baked Oatmeal",
    category: "Breakfast",
    prepMinutes: 10,
    cookMinutes: 35,
    time: 45,
    servings: 6,
    difficulty: "Easy",
    tag: "Make-ahead breakfast",
    image: img("photo-1517673132405-a56a62b18caf"),
    imageAlt: "A baking dish of oatmeal topped with fruit",
    description:
      "Baked oats with diced apple, cinnamon, and a maple-sweetened custard for breakfast through the week.",
    intro:
      "One pan of baked oatmeal covers several mornings. It sets like a soft bar, so you can cut it into squares and reheat a piece with milk instead of cooking breakfast from scratch.",
    keywords: ["apple cinnamon baked oatmeal", "make ahead breakfast recipe", "easy baked oatmeal"],
    ingredients: [
      "2 cups old-fashioned rolled oats",
      "1 tsp baking powder",
      "1 1/2 tsp ground cinnamon",
      "1/4 tsp salt",
      "1 1/2 cups milk",
      "1 large egg",
      "1/3 cup maple syrup",
      "2 tbsp melted butter or neutral oil",
      "1 tsp vanilla extract",
      "1 large apple, diced",
      "1/4 cup chopped walnuts, optional",
    ],
    steps: [
      "Heat the oven to 350°F (175°C). Grease an 8-inch square baking dish.",
      "Mix the oats, baking powder, cinnamon, and salt.",
      "In another bowl, whisk the milk, egg, maple syrup, melted butter, and vanilla.",
      "Pour the wet ingredients into the dry ingredients and stir in the apple.",
      "Spread the batter in the dish, add the walnuts if you are using them, and bake 30 to 35 minutes, until the center is set and the edges are golden.",
      "Cool for 10 minutes. Serve warm with milk or yogurt.",
    ],
    tips: "Reheat a portion with a splash of milk so the oats stay soft.",
    storage:
      "Cool, cover, and refrigerate for up to 4 days. Freeze squares for up to 2 months and thaw them overnight in the refrigerator.",
    substitutions: [
      "Pear can replace the apple in the same amount.",
      "Any milk works, including unsweetened oat or dairy milk.",
      "Pecans can replace the walnuts.",
    ],
    season: "Fall breakfast",
  },
  {
    slug: "crispy-black-bean-tacos",
    title: "Crispy Black Bean Tacos",
    category: "Vegetarian",
    prepMinutes: 10,
    cookMinutes: 12,
    time: 22,
    servings: 4,
    difficulty: "Easy",
    tag: "Budget friendly",
    image: img("photo-1551504734-5ee1c4a1479b"),
    imageAlt: "Crisp tacos filled with beans, herbs, and fresh toppings",
    description:
      "Skillet-crisped corn tortillas filled with seasoned black beans, cheese, avocado, and salsa.",
    intro:
      "Mashing part of the beans helps them stay in the tortilla while the outside crisps. Cook the tacos in batches and keep the finished ones on a rack so the bottoms do not steam.",
    keywords: ["easy black bean tacos", "vegetarian taco recipe", "quick meatless dinner"],
    ingredients: [
      "1 can (15 oz) black beans, drained and rinsed",
      "1 tsp olive oil",
      "1/2 tsp ground cumin",
      "1/2 tsp smoked paprika",
      "8 small corn tortillas",
      "1 cup shredded Monterey Jack or cheddar",
      "1 avocado, sliced",
      "1 cup shredded lettuce",
      "Salsa and lime wedges",
      "Salt, to taste",
    ],
    steps: [
      "Mash about one-third of the beans with a fork. Leave the rest whole.",
      "Heat the oil in a skillet over medium heat. Cook the beans with cumin, paprika, and a pinch of salt for 3 minutes.",
      "Warm the tortillas so they bend. Fill one half of each with beans and a little cheese.",
      "Fold and cook in a lightly oiled skillet for 2 to 3 minutes per side, until crisp and the cheese has melted.",
      "Serve with avocado, lettuce, salsa, and lime.",
    ],
    tips: "Do not overfill the tortillas. Keep cooked tacos warm on a rack in a 200°F (95°C) oven.",
    storage:
      "The bean filling keeps for 4 days in the refrigerator. Crisp the tortillas when you eat them. Avocado should be cut at serving time.",
    substitutions: [
      "Pinto beans can replace black beans.",
      "Flour tortillas work if you wipe out extra oil so they crisp instead of fry hard.",
      "Jack cheese can be left out. The tacos will not bind quite as well, so mash a few more beans.",
    ],
    season: "Anytime favorite",
  },
  {
    slug: "one-pot-tomato-basil-pasta",
    title: "One-Pot Tomato Basil Pasta",
    category: "Dinner",
    prepMinutes: 10,
    cookMinutes: 15,
    time: 25,
    servings: 4,
    difficulty: "Easy",
    tag: "One-pot wonder",
    image: img("photo-1473093295043-cdd812d0e601"),
    imageAlt: "A skillet of tomato pasta with basil leaves on top",
    description:
      "Linguine cooked in one pot with cherry tomatoes, garlic, basil, and Parmesan.",
    intro:
      "The pasta cooks directly in the seasoned liquid, and the starch makes the sauce. Use a wide pot so the noodles lie mostly flat, and stir often during the last few minutes.",
    keywords: ["one pot pasta recipe", "easy tomato basil pasta", "30 minute pasta dinner"],
    ingredients: [
      "12 oz linguine or spaghetti",
      "1 pint cherry tomatoes, halved",
      "4 cloves garlic, thinly sliced",
      "4 1/2 cups vegetable broth or water",
      "2 tbsp olive oil",
      "1/2 tsp red pepper flakes, optional",
      "1/2 tsp salt, plus more to taste",
      "1/2 cup grated Parmesan",
      "1/2 cup fresh basil leaves",
      "Black pepper",
    ],
    steps: [
      "Put the pasta, tomatoes, garlic, broth, olive oil, red pepper flakes, and salt in a wide pot.",
      "Bring to a boil, then keep a lively simmer. Cook uncovered for 9 to 12 minutes, stirring often.",
      "The pasta should be al dente and most of the liquid should look like a glossy sauce. Add a splash of water if the pot goes dry early.",
      "Take the pot off the heat. Fold in the Parmesan and basil.",
      "Season with black pepper and more salt if it needs it. Serve from the pot.",
    ],
    tips: "Different pasta shapes need different amounts of liquid. Check at 8 minutes.",
    storage:
      "Refrigerate for up to 4 days. Reheat in a skillet with a splash of water until hot.",
    substitutions: [
      "Any long pasta can replace linguine. Thick shapes may need extra liquid and a few more minutes.",
      "Parsley can stand in for basil.",
      "A drained can of diced tomatoes can replace the cherry tomatoes.",
    ],
    season: "Weeknight staple",
  },
  {
    slug: "pumpkin-spice-pancakes",
    title: "Fluffy Pumpkin Spice Pancakes",
    category: "Breakfast",
    prepMinutes: 10,
    cookMinutes: 15,
    time: 25,
    servings: 4,
    difficulty: "Easy",
    tag: "Seasonal",
    image: img("photo-1528207776546-365bb710ee93"),
    imageAlt: "A stack of pancakes with syrup on a plate",
    description:
      "Soft pumpkin pancakes seasoned with pumpkin pie spice for a fall breakfast.",
    intro:
      "Pumpkin purée makes the batter thick, so stop stirring as soon as the flour disappears. A few lumps are better than a tough pancake. Cook them when the skillet is hot enough that a drop of water skitters.",
    keywords: ["pumpkin pancake recipe", "easy pumpkin pancakes", "fall breakfast recipe"],
    ingredients: [
      "1 1/2 cups all-purpose flour",
      "2 tbsp brown sugar",
      "2 tsp baking powder",
      "1 tsp pumpkin pie spice",
      "1/4 tsp salt",
      "3/4 cup milk",
      "1/2 cup pumpkin purée",
      "1 large egg",
      "2 tbsp melted butter",
      "1 tsp vanilla extract",
      "Maple syrup, to serve",
    ],
    steps: [
      "Whisk the flour, brown sugar, baking powder, pumpkin pie spice, and salt.",
      "In another bowl, whisk the milk, pumpkin, egg, melted butter, and vanilla until smooth.",
      "Fold the wet ingredients into the dry ingredients just until combined.",
      "Heat a lightly greased skillet over medium heat. Pour about 1/4 cup of batter for each pancake.",
      "Cook until bubbles sit on the surface and the edges look set, about 2 minutes. Flip and cook 1 to 2 minutes more.",
      "Serve warm with maple syrup.",
    ],
    tips: "If the batter is too thick to pour, add milk one tablespoon at a time.",
    storage:
      "Cool leftovers on a rack, then refrigerate for 3 days. Reheat in a toaster or a dry skillet. Freeze with parchment between pancakes for up to a month.",
    substitutions: [
      "1/2 teaspoon cinnamon plus 1/4 teaspoon each of ginger and nutmeg can replace pumpkin pie spice.",
      "A neutral oil can replace the melted butter.",
      "Use plain canned pumpkin, not pumpkin pie filling.",
    ],
    season: "Fall brunch",
  },
  {
    slug: "lemon-garlic-salmon-and-broccoli",
    title: "Lemon Garlic Salmon and Broccoli",
    category: "Dinner",
    prepMinutes: 10,
    cookMinutes: 18,
    time: 28,
    servings: 4,
    difficulty: "Easy",
    tag: "Sheet-pan dinner",
    image: img("photo-1519708227418-c8fd9a32b7a2"),
    imageAlt: "A baked salmon fillet with lemon on a sheet pan",
    description:
      "Salmon fillets and broccoli roast on one pan with garlic, lemon, and olive oil.",
    intro:
      "Salmon and broccoli share a pan if the broccoli is cut small and the salmon goes in only when the oven is already hot. Pull the fish at 145°F (63°C) so it stays moist.",
    keywords: ["sheet pan salmon and broccoli", "easy salmon dinner", "30 minute fish dinner"],
    ingredients: [
      "4 salmon fillets, about 5 oz each",
      "4 cups small broccoli florets",
      "2 tbsp olive oil",
      "3 cloves garlic, minced",
      "1 lemon, half sliced and half juiced",
      "1/2 tsp salt",
      "1/4 tsp black pepper",
      "Cooked rice, to serve",
    ],
    steps: [
      "Heat the oven to 425°F (220°C). Toss the broccoli with 1 tablespoon of oil, half the garlic, salt, and pepper.",
      "Spread the broccoli on a rimmed sheet pan and roast for 8 minutes.",
      "Pat the salmon dry. Rub it with the remaining oil and garlic, and season with salt and pepper.",
      "Move the broccoli to the edges. Add the salmon and lemon slices. Roast 8 to 12 minutes, until the thickest fillet reaches 145°F (63°C) and the fish flakes.",
      "Squeeze the remaining lemon over the pan and serve with rice.",
    ],
    tips: "If the broccoli is browning too fast, tent that side of the pan with foil while the salmon finishes.",
    storage:
      "Refrigerate within two hours and eat within 2 days. Reheat gently, covered, just until warm. Fish dries out if it boils again.",
    substitutions: [
      "Green beans can replace the broccoli. Add them with the salmon if they are thin.",
      "Trout fillets work at the same temperature. They may finish a few minutes sooner.",
    ],
    season: "Weeknight staple",
  },
  {
    slug: "beef-and-broccoli-stir-fry",
    title: "Beef and Broccoli Stir-Fry",
    category: "Dinner",
    prepMinutes: 15,
    cookMinutes: 10,
    time: 25,
    servings: 4,
    difficulty: "Easy",
    tag: "20-minute dinner",
    image: img("photo-1555939594-58d7cb561ad1"),
    imageAlt: "Grilled meat skewers with peppers, potatoes, and sauces",
    description:
      "Thinly sliced beef and broccoli in a soy-garlic sauce, served over rice.",
    intro:
      "Slice the beef while the rice cooks, and keep the pan very hot. Crowding the skillet steams the meat. Cook the beef in two batches if your pan is smaller than 12 inches.",
    keywords: ["beef and broccoli stir fry recipe", "easy beef stir fry", "30 minute beef dinner"],
    ingredients: [
      "1 lb flank or sirloin steak, sliced thin against the grain",
      "4 cups broccoli florets",
      "2 tbsp neutral oil",
      "3 cloves garlic, minced",
      "1 tbsp grated fresh ginger",
      "1/3 cup low-sodium soy sauce",
      "1/3 cup water",
      "1 tbsp cornstarch",
      "1 tbsp honey",
      "Cooked rice, to serve",
    ],
    steps: [
      "Stir the soy sauce, water, cornstarch, and honey together and set the sauce aside.",
      "Heat 1 tablespoon of oil in a large skillet over high heat. Sear the beef in a single layer for 1 to 2 minutes, until browned. Transfer it to a plate.",
      "Add the remaining oil and the broccoli. Stir-fry for 3 minutes. Add a splash of water, cover, and cook 2 minutes, until the broccoli is bright and crisp-tender.",
      "Add the garlic and ginger and stir for 30 seconds.",
      "Return the beef to the pan, pour in the sauce, and cook 1 minute, until the sauce is glossy. The beef should be hot and no longer raw.",
      "Serve over rice.",
    ],
    tips: "Partially freeze the steak for 15 minutes if it is hard to slice thin.",
    storage:
      "Refrigerate for up to 3 days. Reheat in a skillet with a spoon of water until steaming, 165°F (74°C).",
    substitutions: [
      "Tamari can replace soy sauce for a gluten-free version. Check the label.",
      "Snow peas or green beans can replace half of the broccoli.",
      "Chicken breast, sliced thin and cooked to 165°F (74°C), can replace the beef.",
    ],
    season: "Anytime favorite",
  },
  {
    slug: "turkey-taco-skillet",
    title: "Turkey Taco Skillet",
    category: "Dinner",
    prepMinutes: 10,
    cookMinutes: 20,
    time: 30,
    servings: 4,
    difficulty: "Easy",
    tag: "Family dinner",
    image: img("photo-1565299585323-38d6b0865b47"),
    imageAlt: "Chickpea and sweet potato tacos being finished with lime",
    description:
      "Ground turkey simmered with peppers, tomatoes, and taco seasoning, served with tortillas.",
    intro:
      "This is a one-skillet taco filling you can portion into tortillas or over rice. Brown the turkey until no pink remains, then let the tomatoes reduce so the filling is not watery.",
    keywords: ["ground turkey taco recipe", "easy turkey skillet", "quick taco dinner"],
    ingredients: [
      "1 tbsp olive oil",
      "1 lb ground turkey",
      "1 onion, diced",
      "1 bell pepper, diced",
      "2 cloves garlic, minced",
      "1 tbsp chili powder",
      "1 tsp ground cumin",
      "1/2 tsp smoked paprika",
      "1 can (15 oz) diced tomatoes",
      "1/2 tsp salt",
      "8 small tortillas",
      "Shredded lettuce, cheese, and lime, to serve",
    ],
    steps: [
      "Heat the oil in a large skillet over medium heat. Cook the onion and pepper for 4 minutes.",
      "Add the turkey and break it up. Cook until no longer pink and the thickest part of the crumbles reaches 165°F (74°C), about 6 minutes.",
      "Stir in the garlic, chili powder, cumin, paprika, and salt for 30 seconds.",
      "Add the tomatoes and simmer for 8 minutes, until the sauce thickens.",
      "Warm the tortillas and serve the skillet with lettuce, cheese, and lime.",
    ],
    tips: "If the turkey releases a lot of liquid, spoon some off before adding the tomatoes so the filling browns.",
    storage:
      "Refrigerate the filling for up to 4 days. Reheat to 165°F (74°C). Warm tortillas separately so they do not get soggy.",
    substitutions: [
      "Ground chicken works the same way and also needs to reach 165°F (74°C).",
      "A 4-ounce can of diced green chiles can replace the bell pepper.",
      "Serve it over rice instead of tortillas.",
    ],
    season: "Anytime favorite",
  },
  {
    slug: "honey-garlic-chicken-thighs",
    title: "Honey Garlic Chicken Thighs",
    category: "Dinner",
    prepMinutes: 10,
    cookMinutes: 25,
    time: 35,
    servings: 4,
    difficulty: "Easy",
    tag: "Skillet dinner",
    image: img("photo-1565557623262-b51c2513a641"),
    imageAlt: "Chicken in a spiced tomato sauce served with flatbread",
    description:
      "Boneless chicken thighs with a sticky honey, soy, and garlic pan sauce.",
    intro:
      "Sear the thighs skin-side or smooth-side down until they take on color, then finish them in a small amount of sauce. The honey burns if the pan is screaming hot, so turn the heat down before it goes in.",
    keywords: ["honey garlic chicken recipe", "easy chicken thigh dinner", "30 minute chicken thighs"],
    ingredients: [
      "1 1/2 lb boneless, skinless chicken thighs",
      "1/2 tsp salt",
      "1/4 tsp black pepper",
      "1 tbsp olive oil",
      "4 cloves garlic, minced",
      "1/3 cup low-sodium soy sauce",
      "3 tbsp honey",
      "1 tbsp rice vinegar or apple cider vinegar",
      "1/4 cup water",
      "Cooked rice and sliced green onion, to serve",
    ],
    steps: [
      "Pat the thighs dry and season them with salt and pepper.",
      "Heat the oil in a skillet over medium-high heat. Cook the thighs for 5 to 6 minutes per side, until browned.",
      "Add the garlic and stir for 30 seconds around the chicken.",
      "Whisk the soy sauce, honey, vinegar, and water, then pour it into the pan. Lower the heat to medium.",
      "Simmer for 8 to 10 minutes, turning once, until the thickest thigh reaches 165°F (74°C) and the sauce is syrupy.",
      "Rest for 3 minutes. Slice and serve over rice with green onion and the pan sauce.",
    ],
    tips: "If the sauce reduces too fast, add a splash of water. If it is thin, simmer it for another minute after the chicken comes out.",
    storage:
      "Refrigerate for up to 4 days. Reheat covered with a spoon of water until the chicken reaches 165°F (74°C).",
    substitutions: [
      "Chicken breasts work if you pound them to an even thickness and check the temperature early.",
      "Maple syrup can replace the honey.",
    ],
    season: "Weeknight staple",
  },
  {
    slug: "sheet-pan-chicken-fajitas",
    title: "Sheet-Pan Chicken Fajitas",
    category: "Dinner",
    prepMinutes: 15,
    cookMinutes: 20,
    time: 35,
    servings: 4,
    difficulty: "Easy",
    tag: "Sheet-pan dinner",
    image: img("photo-1604908176997-125f25cc6f3d"),
    imageAlt: "Chicken pieces cooked with peppers and herbs",
    description:
      "Sliced chicken, peppers, and onion roasted with chili powder and lime, served in tortillas.",
    intro:
      "Cutting the chicken into strips lets it finish with the peppers. Do not pile the pan. A crowded sheet pan steams the onions instead of browning them.",
    keywords: ["sheet pan chicken fajitas", "easy chicken fajita recipe", "quick fajita dinner"],
    ingredients: [
      "1 1/4 lb boneless, skinless chicken breast, sliced into strips",
      "2 bell peppers, sliced",
      "1 red onion, sliced",
      "2 tbsp olive oil",
      "1 tbsp chili powder",
      "1 tsp ground cumin",
      "1 tsp smoked paprika",
      "1/2 tsp salt",
      "1 lime, juiced",
      "8 flour tortillas",
      "Salsa and cilantro, to serve",
    ],
    steps: [
      "Heat the oven to 425°F (220°C).",
      "Toss the chicken, peppers, and onion with the oil, chili powder, cumin, paprika, and salt.",
      "Spread everything in a single layer on a large rimmed sheet pan.",
      "Roast for 18 to 22 minutes, stirring once, until the chicken reaches 165°F (74°C) and the peppers are tender.",
      "Squeeze the lime over the pan. Serve in warm tortillas with salsa and cilantro.",
    ],
    tips: "Use two pans if the food overlaps. Overlap is the main reason fajitas come out soggy.",
    storage:
      "Refrigerate the chicken and vegetables for up to 4 days. Reheat in a skillet to 165°F (74°C) and warm fresh tortillas.",
    substitutions: [
      "Turkey cutlets, sliced thin, can replace the chicken and still need to reach 165°F (74°C).",
      "Corn tortillas can replace flour tortillas.",
    ],
    season: "Anytime favorite",
  },
  {
    slug: "skillet-turkey-meatballs",
    title: "Skillet Turkey Meatballs",
    category: "Dinner",
    prepMinutes: 15,
    cookMinutes: 20,
    time: 35,
    servings: 4,
    difficulty: "Easy",
    tag: "Family dinner",
    image: img("photo-1621996346565-e3dbc646d9a9"),
    imageAlt: "Penne tossed with a tomato meat sauce",
    description:
      "Browned turkey meatballs simmered in marinara and served with spaghetti.",
    intro:
      "A short sear gives the meatballs a crust, and the sauce finishes the center. Use a thermometer. Turkey is done at 165°F (74°C), even if the outside already looks brown.",
    keywords: ["easy turkey meatball recipe", "turkey meatballs and spaghetti", "30 minute meatball dinner"],
    ingredients: [
      "1 lb ground turkey",
      "1/2 cup dry breadcrumbs",
      "1 egg",
      "1/4 cup grated Parmesan",
      "1 tsp Italian seasoning",
      "1/2 tsp salt",
      "1 tbsp olive oil",
      "2 cups marinara sauce",
      "12 oz spaghetti, cooked",
      "Chopped parsley, to finish",
    ],
    steps: [
      "Mix the turkey, breadcrumbs, egg, Parmesan, Italian seasoning, and salt until just combined. Form 16 meatballs.",
      "Heat the oil in a large skillet over medium heat. Brown the meatballs for about 6 minutes, turning until all sides have color.",
      "Pour in the marinara, cover, and simmer for 12 to 14 minutes.",
      "Check the center of a meatball. It should read 165°F (74°C).",
      "Serve over spaghetti and finish with parsley.",
    ],
    tips: "Wet your hands before rolling so the mixture does not stick. Do not compact the meatballs or they turn dense.",
    storage:
      "Refrigerate meatballs and sauce for up to 4 days, separate from the pasta if you can. Reheat the sauce and meatballs to 165°F (74°C).",
    substitutions: [
      "Ground chicken can replace the turkey at the same temperature.",
      "Crushed saltines can replace the breadcrumbs.",
    ],
    season: "Weeknight staple",
  },
  {
    slug: "sausage-pepper-and-onion-pasta",
    title: "Sausage, Pepper, and Onion Pasta",
    category: "Dinner",
    prepMinutes: 10,
    cookMinutes: 20,
    time: 30,
    servings: 4,
    difficulty: "Easy",
    tag: "One-pan pasta",
    image: img("photo-1551183053-bf91a1d81141"),
    imageAlt: "Skillet pasta with beef, spinach, and tomatoes",
    description:
      "Italian sausage, sweet peppers, and onion tossed with short pasta and a light tomato sauce.",
    intro:
      "Brown the sausage first so the peppers cook in the drippings. Use fully cooked smoked sausage if you want a faster pan, or raw Italian sausage if you want it crumbled.",
    keywords: ["sausage and peppers pasta", "easy sausage pasta recipe", "30 minute pasta dinner"],
    ingredients: [
      "12 oz short pasta, such as penne",
      "1 tbsp olive oil",
      "3/4 lb raw Italian sausage, casings removed",
      "1 onion, sliced",
      "2 bell peppers, sliced",
      "2 cloves garlic, minced",
      "1 can (15 oz) crushed tomatoes",
      "1/2 tsp salt",
      "1/4 tsp black pepper",
      "1/4 cup chopped parsley",
    ],
    steps: [
      "Boil the pasta in salted water until al dente. Reserve 1/2 cup of the pasta water, then drain.",
      "Meanwhile, heat the oil in a large skillet over medium heat. Cook the sausage, breaking it up, until browned and the center reaches 160°F (71°C), about 7 minutes.",
      "Add the onion and peppers. Cook for 6 minutes, until softened.",
      "Stir in the garlic for 30 seconds. Add the tomatoes, salt, and pepper, and simmer for 5 minutes.",
      "Toss in the pasta and enough pasta water to make a light sauce. Finish with parsley.",
    ],
    tips: "If you use smoked sausage that is already cooked, slice it and brown it for flavor, then follow the same pepper steps.",
    storage:
      "Refrigerate for up to 4 days. Reheat with a splash of water until the sausage is steaming hot, 165°F (74°C).",
    substitutions: [
      "Chicken sausage works. Cook raw chicken sausage to 165°F (74°C).",
      "Zucchini slices can replace one of the peppers. Add them near the end so they do not fall apart.",
    ],
    season: "Weeknight staple",
  },
  {
    slug: "baked-pork-chops-with-apples",
    title: "Baked Pork Chops with Apples",
    category: "Dinner",
    prepMinutes: 10,
    cookMinutes: 25,
    time: 35,
    servings: 4,
    difficulty: "Easy",
    tag: "Fall favorite",
    image: img("photo-1432139555190-58524dae6a55"),
    imageAlt: "A seared pork chop topped with diced apples and broccolini",
    description:
      "Bone-in pork chops baked with sliced apples, onion, and a little Dijon.",
    intro:
      "A brief sear, then the oven, keeps the chops from drying out while the apples soften. Pull them at 145°F (63°C) and let them rest for 3 minutes.",
    keywords: ["baked pork chops and apples", "easy pork chop recipe", "fall pork chop dinner"],
    ingredients: [
      "4 bone-in pork chops, about 3/4 inch thick",
      "1/2 tsp salt",
      "1/4 tsp black pepper",
      "1 tbsp olive oil",
      "2 apples, sliced",
      "1 small onion, sliced",
      "1 tbsp Dijon mustard",
      "1 tbsp maple syrup",
      "1/2 tsp dried thyme",
      "1/4 cup water",
    ],
    steps: [
      "Heat the oven to 400°F (200°C). Season the chops with salt and pepper.",
      "Heat the oil in an oven-safe skillet over medium-high heat. Sear the chops for 2 to 3 minutes per side. Transfer them to a plate.",
      "Add the apples and onion to the skillet and stir for 2 minutes. Whisk in the Dijon, maple syrup, thyme, and water.",
      "Nestle the chops back in. Bake for 12 to 16 minutes, until the center of each chop reaches 145°F (63°C).",
      "Rest for 3 minutes before serving with the apples and pan juices.",
    ],
    tips: "Thick chops need the longer end of the bake time. Thin chops can overshoot 145°F quickly, so start checking early.",
    storage:
      "Refrigerate within two hours for up to 3 days. Reheat gently to 165°F (74°C) so the edges do not dry out.",
    substitutions: [
      "Pears can replace the apples.",
      "Boneless chops work. They cook faster, so check the temperature sooner.",
    ],
    season: "October pick",
  },
  {
    slug: "shrimp-garlic-pasta",
    title: "Shrimp Garlic Pasta",
    category: "Dinner",
    prepMinutes: 10,
    cookMinutes: 15,
    time: 25,
    servings: 4,
    difficulty: "Easy",
    tag: "20-minute dinner",
    image: img("photo-1563379926898-05f4575a45d8"),
    imageAlt: "Shrimp and noodles in a skillet with cherry tomatoes",
    description:
      "A fast pasta of shrimp, garlic, lemon, and parsley finished with pasta water.",
    intro:
      "Shrimp turn from translucent to pink in a few minutes. Take them out of the pan before you build the sauce, then add them back so they do not go rubbery.",
    keywords: ["garlic shrimp pasta recipe", "easy shrimp scampi pasta", "20 minute shrimp dinner"],
    ingredients: [
      "12 oz spaghetti",
      "1 lb peeled shrimp",
      "3 tbsp olive oil",
      "4 cloves garlic, sliced",
      "1/2 tsp red pepper flakes, optional",
      "1/2 tsp salt",
      "1 lemon, juiced",
      "1/4 cup chopped parsley",
      "Black pepper",
    ],
    steps: [
      "Cook the spaghetti in salted water until al dente. Reserve 3/4 cup of pasta water and drain the pasta.",
      "Pat the shrimp dry. Heat 1 tablespoon of oil in a large skillet over medium-high heat.",
      "Cook the shrimp for 1 to 2 minutes per side, until pink and opaque. Transfer them to a plate.",
      "Lower the heat to medium. Add the remaining oil, garlic, and red pepper flakes. Stir for 30 seconds.",
      "Add the pasta, pasta water, lemon juice, and salt. Toss for 1 minute.",
      "Return the shrimp to the pan just to warm through. Finish with parsley and black pepper.",
    ],
    tips: "If the shrimp are frozen, thaw them in the refrigerator and pat them very dry or they will steam.",
    storage:
      "Refrigerate for up to 2 days. Reheat gently in a skillet with a splash of water. Do not boil the shrimp again.",
    substitutions: [
      "Linguine can replace spaghetti.",
      "A handful of spinach can go in with the pasta water if you want a green in the same pan.",
    ],
    season: "Weeknight staple",
  },
  {
    slug: "spinach-mushroom-frittata",
    title: "Spinach and Mushroom Frittata",
    category: "Breakfast",
    prepMinutes: 10,
    cookMinutes: 20,
    time: 30,
    servings: 6,
    difficulty: "Easy",
    tag: "Make-ahead breakfast",
    image: img("photo-1525351484163-7529414344d8"),
    imageAlt: "A fried egg on avocado toast",
    description:
      "A baked egg dish with mushrooms, spinach, and cheese that slices into breakfast portions.",
    intro:
      "Cook the vegetables before the eggs go in, or the frittata weeps. The center should be just set, not browned hard. It is easier to slice after a short rest.",
    keywords: ["spinach mushroom frittata recipe", "easy egg breakfast", "make ahead breakfast"],
    ingredients: [
      "8 large eggs",
      "1/4 cup milk",
      "1/2 tsp salt",
      "1/4 tsp black pepper",
      "1 tbsp olive oil",
      "8 oz mushrooms, sliced",
      "2 cups baby spinach",
      "2 cloves garlic, minced",
      "1/2 cup shredded cheddar",
    ],
    steps: [
      "Heat the oven to 375°F (190°C). Whisk the eggs, milk, salt, and pepper.",
      "Heat the oil in a 10-inch oven-safe skillet over medium heat. Cook the mushrooms for 5 minutes, until they release liquid and it evaporates.",
      "Add the garlic and spinach. Stir until the spinach wilts.",
      "Pour in the eggs and sprinkle on the cheese. Cook for 2 minutes without stirring, until the edge starts to set.",
      "Bake for 12 to 16 minutes, until the center is set and a knife comes out clean.",
      "Rest for 5 minutes, then slice.",
    ],
    tips: "If your skillet handle is not oven-safe, wrap it in a few layers of foil or start the eggs in a pie dish.",
    storage:
      "Refrigerate slices for up to 4 days. Reheat covered until just warm. Freeze for up to a month if wrapped well.",
    substitutions: [
      "Any melting cheese can replace the cheddar.",
      "Chopped kale can replace the spinach. Wilt it a minute longer.",
    ],
    season: "Anytime favorite",
  },
  {
    slug: "veggie-breakfast-burritos",
    title: "Veggie Breakfast Burritos",
    category: "Breakfast",
    prepMinutes: 15,
    cookMinutes: 15,
    time: 30,
    servings: 4,
    difficulty: "Easy",
    tag: "Make-ahead breakfast",
    image: img("photo-1484723091739-30a097e8f929"),
    imageAlt: "French toast stacked with banana slices and blueberries",
    description:
      "Scrambled eggs, peppers, beans, and cheese rolled into burritos you can refrigerate or freeze.",
    intro:
      "Drain the vegetables well before they meet the eggs. Extra moisture makes the tortilla soggy by the next morning. Wrap each burrito in foil if you plan to save it.",
    keywords: ["breakfast burrito recipe", "make ahead breakfast burritos", "freezer breakfast burritos"],
    ingredients: [
      "6 large eggs",
      "1 tbsp olive oil",
      "1 bell pepper, diced",
      "2 green onions, sliced",
      "1 cup canned black beans, rinsed",
      "1/2 tsp ground cumin",
      "1/4 tsp salt",
      "1 cup shredded cheddar",
      "4 large flour tortillas",
      "Salsa, to serve",
    ],
    steps: [
      "Whisk the eggs with the salt.",
      "Heat the oil in a skillet over medium heat. Cook the pepper for 4 minutes. Add the beans and cumin and warm them through. Spoon the mixture into a bowl.",
      "Scramble the eggs in the same skillet over medium-low heat until just set. Take them off the heat while they still look slightly soft.",
      "Warm the tortillas. Divide the eggs, bean mixture, cheese, and green onions among them.",
      "Fold the sides in and roll tightly. Serve with salsa, or wrap and chill.",
    ],
    tips: "Let the filling cool for a few minutes before rolling if you are freezing the burritos. Steam inside the wrap makes them icy and wet.",
    storage:
      "Refrigerate for up to 3 days. Freeze wrapped burritos for up to 2 months. Thaw overnight in the refrigerator and reheat in a covered skillet or a 350°F (175°C) oven until hot, about 165°F (74°C) in the center.",
    substitutions: [
      "Pinto beans can replace black beans.",
      "A handful of spinach can go in with the peppers.",
    ],
    season: "Anytime favorite",
  },
  {
    slug: "berry-overnight-oats",
    title: "Berry Overnight Oats",
    category: "Breakfast",
    prepMinutes: 10,
    cookMinutes: 0,
    time: 10,
    servings: 2,
    difficulty: "Easy",
    tag: "No-cook breakfast",
    image: img("photo-1490474418585-ba9bad8fd0ea"),
    imageAlt: "Jars of overnight oats topped with fresh berries",
    description:
      "Rolled oats soaked overnight in milk with berries and a spoon of yogurt.",
    intro:
      "Overnight oats are stirred at night and eaten cold, or warmed, in the morning. Use rolled oats. Instant oats turn pasty, and steel-cut oats stay too hard for this method.",
    keywords: ["overnight oats recipe", "easy berry overnight oats", "no cook breakfast"],
    ingredients: [
      "1 cup old-fashioned rolled oats",
      "1 cup milk",
      "1/2 cup plain yogurt",
      "1 tbsp maple syrup or honey",
      "1/2 tsp vanilla extract",
      "1 cup berries",
      "Pinch of salt",
    ],
    steps: [
      "Stir the oats, milk, yogurt, maple syrup, vanilla, and salt in a jar or container.",
      "Fold in half of the berries. Cover and refrigerate for at least 6 hours, or overnight.",
      "In the morning, loosen with a splash of milk if the oats are thicker than you like.",
      "Top with the remaining berries and eat cold, or warm the base gently before adding the fresh berries.",
    ],
    tips: "A 1:1 ratio of oats to milk is a starting point. Add more milk in the morning rather than at night if you want them softer.",
    storage:
      "Keep covered in the refrigerator for up to 3 days. The berries soften as they sit, which is expected.",
    substitutions: [
      "Any milk works. Thicker yogurt makes a denser cup.",
      "Diced apple and cinnamon can replace the berries.",
    ],
    season: "Anytime favorite",
  },
  {
    slug: "potato-and-egg-skillet",
    title: "Potato and Egg Skillet",
    category: "Breakfast",
    prepMinutes: 10,
    cookMinutes: 20,
    time: 30,
    servings: 4,
    difficulty: "Easy",
    tag: "Skillet breakfast",
    image: img("photo-1482049016688-2d3e1b311543"),
    imageAlt: "Sliced eggs and avocado on toast with spinach",
    description:
      "Crisped diced potatoes with peppers and eggs cooked in the same skillet.",
    intro:
      "The potatoes need a head start and enough oil to brown. Covering the pan at the end sets the eggs without drying the potatoes you already crisped.",
    keywords: ["potato and egg breakfast skillet", "easy breakfast hash", "quick egg and potato breakfast"],
    ingredients: [
      "1 lb potatoes, cut into 1/2-inch dice",
      "2 tbsp olive oil",
      "1 bell pepper, diced",
      "1/2 tsp salt",
      "1/4 tsp black pepper",
      "1/2 tsp smoked paprika",
      "4 large eggs",
      "2 green onions, sliced",
    ],
    steps: [
      "Heat the oil in a large skillet over medium heat. Add the potatoes in a single layer.",
      "Cook for 12 to 14 minutes, stirring every few minutes, until the potatoes are tender and browned.",
      "Add the pepper, salt, black pepper, and paprika. Cook for 3 minutes.",
      "Make four wells in the potatoes. Crack an egg into each. Cover and cook for 3 to 5 minutes, until the whites are set and the yolks are as firm as you like.",
      "Sprinkle with green onions and serve.",
    ],
    tips: "If the potatoes are still firm at 10 minutes, add a tablespoon of water and cover for 2 minutes, then uncover to crisp them again.",
    storage:
      "This is best the morning you cook it. Leftover potatoes and fully set eggs keep for 2 days and can be reheated in a skillet. Do not save eggs with runny yolks.",
    substitutions: [
      "Sweet potato can replace half of the potato. It browns faster, so watch it.",
      "A drained can of diced green chiles can replace the bell pepper.",
    ],
    season: "Anytime favorite",
  },
  {
    slug: "banana-oat-pancakes",
    title: "Banana Oat Pancakes",
    category: "Breakfast",
    prepMinutes: 10,
    cookMinutes: 15,
    time: 25,
    servings: 4,
    difficulty: "Easy",
    tag: "Weekend breakfast",
    image: img("photo-1506084868230-bb9d95c24759"),
    imageAlt: "A stack of pancakes with blueberries and syrup",
    description:
      "Mashed banana and oat pancakes with no refined sugar in the batter.",
    intro:
      "Ripe bananas do the sweetening. Mash them until few lumps remain, then mix the batter only until the oats are wet. These pancakes are softer than a diner stack, so flip them gently.",
    keywords: ["banana oat pancakes", "easy banana pancake recipe", "healthy pancake recipe"],
    ingredients: [
      "2 ripe bananas, mashed",
      "2 large eggs",
      "3/4 cup milk",
      "1 tsp vanilla extract",
      "1 1/2 cups old-fashioned rolled oats",
      "1 tsp baking powder",
      "1/2 tsp ground cinnamon",
      "1/4 tsp salt",
      "Butter or oil, for the pan",
      "Maple syrup or yogurt, to serve",
    ],
    steps: [
      "Whisk the bananas, eggs, milk, and vanilla.",
      "Stir in the oats, baking powder, cinnamon, and salt. Let the batter sit for 5 minutes so the oats soften.",
      "Heat a lightly greased skillet over medium heat.",
      "Cook scant 1/4-cup portions for about 2 minutes per side, until the centers are set.",
      "Serve with maple syrup or yogurt.",
    ],
    tips: "If the first pancake is pale, raise the heat slightly. If it scorches before the center sets, lower the heat.",
    storage:
      "Refrigerate for 3 days and reheat in a toaster or dry skillet. Freeze with parchment between pancakes for a month.",
    substitutions: [
      "A mashed ripe pear can replace one of the bananas if you add an extra teaspoon of maple syrup.",
      "Cinnamon can be left out.",
    ],
    season: "Anytime favorite",
  },
  {
    slug: "creamy-tomato-soup",
    title: "Creamy Tomato Soup",
    category: "Soups",
    prepMinutes: 10,
    cookMinutes: 25,
    time: 35,
    servings: 4,
    difficulty: "Easy",
    tag: "Comfort food",
    image: img("photo-1547592166-23ac45744acd"),
    imageAlt: "A bowl of creamy tomato soup with a spoon",
    description:
      "A blended tomato soup finished with a little cream, served with grilled cheese or bread.",
    intro:
      "Canned tomatoes make this reliable in any season. Blend until smooth, then add the cream off a hard boil so it does not separate. It is a good partner for a leftover grilled cheese night.",
    keywords: ["easy tomato soup recipe", "creamy tomato soup", "quick homemade tomato soup"],
    ingredients: [
      "1 tbsp olive oil",
      "1 onion, diced",
      "2 cloves garlic, minced",
      "1 can (28 oz) whole peeled tomatoes",
      "2 cups low-sodium vegetable broth",
      "1 tsp sugar",
      "1/2 tsp salt",
      "1/4 tsp black pepper",
      "1/3 cup heavy cream or half-and-half",
      "Fresh basil, to finish",
    ],
    steps: [
      "Heat the oil in a pot over medium heat. Cook the onion for 6 minutes, until soft. Add the garlic for 30 seconds.",
      "Add the tomatoes and their juice, the broth, sugar, salt, and pepper. Break the tomatoes up with a spoon.",
      "Simmer for 15 minutes.",
      "Blend until smooth with an immersion blender, or carefully in a blender with the lid vented.",
      "Stir in the cream and warm it through without boiling. Finish with basil.",
    ],
    tips: "The sugar balances acid in canned tomatoes. Taste before you add more.",
    storage:
      "Refrigerate for up to 4 days or freeze for up to 3 months without garnishes. Reheat gently and stir. Do not boil after the cream is in.",
    substitutions: [
      "A can of crushed tomatoes can replace whole peeled tomatoes.",
      "Full-fat coconut milk can replace the cream.",
      "Leave the soup chunky if you do not want to blend it.",
    ],
    season: "Cozy classic",
  },
  {
    slug: "white-bean-kale-soup",
    title: "White Bean and Kale Soup",
    category: "Soups",
    prepMinutes: 10,
    cookMinutes: 25,
    time: 35,
    servings: 6,
    difficulty: "Easy",
    tag: "Pantry soup",
    image: img("photo-1476718406336-bb5a9690ee2a"),
    imageAlt: "A bowl of bean and vegetable soup with greens",
    description:
      "A brothy soup of white beans, tomatoes, carrots, and kale.",
    intro:
      "This is a pantry soup with one fresh green. The beans make it filling without meat. Kale goes in at the end so it softens without turning gray.",
    keywords: ["white bean and kale soup", "easy bean soup recipe", "vegetarian soup recipe"],
    ingredients: [
      "1 tbsp olive oil",
      "1 onion, diced",
      "2 carrots, sliced",
      "2 cloves garlic, minced",
      "1 tsp dried thyme",
      "1 can (15 oz) diced tomatoes",
      "6 cups low-sodium vegetable broth",
      "2 cans (15 oz each) white beans, rinsed",
      "3 cups chopped kale, stems removed",
      "1/2 tsp salt",
      "1 tbsp lemon juice",
      "Grated Parmesan, optional",
    ],
    steps: [
      "Heat the oil in a pot over medium heat. Cook the onion and carrots for 6 minutes.",
      "Add the garlic and thyme for 30 seconds.",
      "Add the tomatoes, broth, beans, and salt. Simmer for 15 minutes.",
      "Stir in the kale and cook for 4 minutes, until tender.",
      "Add the lemon juice. Serve with Parmesan if you like.",
    ],
    tips: "Mash a spoonful of beans against the side of the pot if you want the broth a little thicker.",
    storage:
      "Refrigerate for up to 4 days. The soup thickens as it sits. Add broth when you reheat it until steaming.",
    substitutions: [
      "Spinach can replace the kale. Stir it in during the last minute.",
      "Cannellini, navy, or great northern beans all work.",
      "Chicken broth can replace vegetable broth.",
    ],
    season: "Fall favorite",
  },
  {
    slug: "lentil-vegetable-soup",
    title: "Lentil Vegetable Soup",
    category: "Soups",
    prepMinutes: 15,
    cookMinutes: 35,
    time: 50,
    servings: 6,
    difficulty: "Easy",
    tag: "Pantry soup",
    image: img("photo-1540420773420-3366772f4999"),
    imageAlt: "A bowl of chopped vegetables, greens, and avocado",
    description:
      "Brown lentils simmered with onion, carrot, celery, and tomatoes until the soup is thick.",
    intro:
      "Brown lentils hold their shape better than red lentils and do not need a soak. Rinse them and pick out any small stones before they go into the pot.",
    keywords: ["easy lentil soup recipe", "lentil vegetable soup", "budget dinner soup"],
    ingredients: [
      "1 tbsp olive oil",
      "1 onion, diced",
      "2 carrots, diced",
      "2 celery stalks, diced",
      "3 cloves garlic, minced",
      "1 1/2 cups brown lentils, rinsed",
      "1 can (15 oz) diced tomatoes",
      "6 cups low-sodium vegetable broth",
      "1 tsp ground cumin",
      "1 bay leaf",
      "1 tsp salt",
      "2 tbsp chopped parsley",
      "1 tbsp lemon juice",
    ],
    steps: [
      "Heat the oil in a pot over medium heat. Cook the onion, carrots, and celery for 6 minutes.",
      "Add the garlic and cumin and stir for 30 seconds.",
      "Add the lentils, tomatoes, broth, bay leaf, and salt.",
      "Bring to a boil, then simmer partly covered for 30 to 35 minutes, until the lentils are tender.",
      "Remove the bay leaf. Stir in the parsley and lemon juice. Add water if the soup is thicker than you want.",
    ],
    tips: "Lentils from an older package can take longer. Add broth and keep simmering until they are tender, not crunchy.",
    storage:
      "Refrigerate for up to 4 days or freeze for up to 3 months. Reheat with extra water because lentils keep absorbing liquid.",
    substitutions: [
      "Green lentils can replace brown lentils.",
      "A teaspoon of curry powder can replace the cumin if you want a different pot next time.",
    ],
    season: "Cozy classic",
  },
  {
    slug: "chicken-tortilla-soup",
    title: "Chicken Tortilla Soup",
    category: "Soups",
    prepMinutes: 15,
    cookMinutes: 25,
    time: 40,
    servings: 6,
    difficulty: "Easy",
    tag: "Comfort food",
    image: img("photo-1617093727343-374698b1b08d"),
    imageAlt: "A bowl of creamy soup with chicken, noodles, and vegetables",
    description:
      "A tomato-chile chicken soup topped with baked tortilla strips, avocado, and lime.",
    intro:
      "The soup itself is a simple simmer. The toppings are what make it a tortilla soup, so bake the strips while the pot cooks and add avocado only when you serve.",
    keywords: ["chicken tortilla soup recipe", "easy tortilla soup", "quick chicken soup"],
    ingredients: [
      "1 tbsp olive oil",
      "1 onion, diced",
      "1 bell pepper, diced",
      "3 cloves garlic, minced",
      "1 tbsp chili powder",
      "1 tsp ground cumin",
      "1 can (15 oz) diced tomatoes",
      "6 cups low-sodium chicken broth",
      "2 cups cooked shredded chicken",
      "1 can (15 oz) black beans, rinsed",
      "4 corn tortillas, cut into strips",
      "1 avocado, diced",
      "Lime wedges and cilantro",
      "Salt, to taste",
    ],
    steps: [
      "Heat the oven to 400°F (200°C). Toss the tortilla strips with a teaspoon of oil and a pinch of salt. Bake for 8 to 10 minutes, until crisp. Set them aside.",
      "Heat the remaining oil in a pot over medium heat. Cook the onion and pepper for 5 minutes. Add the garlic, chili powder, and cumin for 30 seconds.",
      "Add the tomatoes and broth. Simmer for 15 minutes.",
      "Stir in the chicken and beans. Heat until the chicken reaches 165°F (74°C). Season with salt.",
      "Serve with tortilla strips, avocado, lime, and cilantro.",
    ],
    tips: "Keep the crisp strips separate from the soup until you eat, or they soften immediately.",
    storage:
      "Refrigerate the soup, without avocado and strips, for up to 4 days. Reheat to 165°F (74°C). Bake fresh strips when you serve leftovers.",
    substitutions: [
      "Rotisserie chicken works if the skin is removed.",
      "Fire-roasted diced tomatoes add a little smoke if you have them.",
      "Leave out the chicken and use vegetable broth for a meatless pot. The beans still make it a meal.",
    ],
    season: "Anytime favorite",
  },
  {
    slug: "chickpea-coconut-curry",
    title: "Chickpea Coconut Curry",
    category: "Vegetarian",
    prepMinutes: 10,
    cookMinutes: 20,
    time: 30,
    servings: 4,
    difficulty: "Easy",
    tag: "One-pot wonder",
    image: img("photo-1455619452474-d2be8b1e70cd"),
    imageAlt: "A bowl of chickpea coconut curry with rice",
    description:
      "Chickpeas simmered in coconut milk with curry powder, spinach, and lime.",
    intro:
      "Bloom the curry powder in oil for half a minute so it tastes toasted instead of raw. Coconut milk should simmer, not boil hard, or the sauce can separate.",
    keywords: ["easy chickpea curry", "chickpea coconut curry recipe", "30 minute vegetarian curry"],
    ingredients: [
      "1 tbsp olive oil",
      "1 onion, diced",
      "3 cloves garlic, minced",
      "1 tbsp grated fresh ginger",
      "1 1/2 tbsp curry powder",
      "2 cans (15 oz each) chickpeas, rinsed",
      "1 can (14 oz) coconut milk",
      "1/2 cup water",
      "3 cups baby spinach",
      "1/2 tsp salt",
      "1 tbsp lime juice",
      "Cooked rice, to serve",
    ],
    steps: [
      "Heat the oil in a pot over medium heat. Cook the onion for 5 minutes.",
      "Add the garlic, ginger, and curry powder. Stir for 30 seconds.",
      "Add the chickpeas, coconut milk, water, and salt. Simmer for 12 minutes.",
      "Stir in the spinach until it wilts. Add the lime juice.",
      "Serve over rice.",
    ],
    tips: "If the curry tastes sharp, another pinch of salt usually fixes it before you add more spice.",
    storage:
      "Refrigerate for up to 4 days. Reheat gently so the coconut milk does not split. The spinach will darken, which is normal.",
    substitutions: [
      "A teaspoon of garam masala plus a teaspoon of turmeric can stand in for curry powder.",
      "Kale, chopped, can replace the spinach if you simmer it for 4 minutes.",
      "Canned lentils can replace one can of chickpeas.",
    ],
    season: "Anytime favorite",
  },
  {
    slug: "vegetable-fried-rice",
    title: "Vegetable Fried Rice",
    category: "Vegetarian",
    prepMinutes: 15,
    cookMinutes: 10,
    time: 25,
    servings: 4,
    difficulty: "Easy",
    tag: "Use-it-up dinner",
    image: img("photo-1512058564366-18510be2db19"),
    imageAlt: "A skillet of rice with shrimp, lemon, and herbs",
    description:
      "Cold rice stir-fried with egg, peas, carrot, and soy sauce.",
    intro:
      "Cold rice is the whole trick. Freshly cooked rice sticks and steams. Spread leftover rice on a plate and refrigerate it, uncovered, for at least a few hours or overnight.",
    keywords: ["easy vegetable fried rice", "leftover rice recipe", "20 minute fried rice"],
    ingredients: [
      "3 cups cold cooked rice",
      "2 tbsp neutral oil",
      "2 eggs, beaten",
      "1 carrot, finely diced",
      "1 cup frozen peas",
      "3 green onions, sliced",
      "2 cloves garlic, minced",
      "2 tbsp low-sodium soy sauce",
      "1 tsp rice vinegar",
    ],
    steps: [
      "Break up the cold rice so there are no large clumps.",
      "Heat 1 tablespoon of oil in a large skillet over high heat. Pour in the eggs and scramble them. Transfer them to a plate.",
      "Add the remaining oil, carrot, and peas. Stir-fry for 2 minutes.",
      "Add the garlic and rice. Spread the rice out and let it sit for 30 seconds, then toss. Repeat once so some grains toast.",
      "Return the eggs to the pan. Add the soy sauce, vinegar, and green onions. Toss and serve.",
    ],
    tips: "Day-old rice from the refrigerator should be cooled quickly after it was first cooked, not left out overnight. See the leftover rice guide if you are unsure.",
    storage:
      "Refrigerate within two hours and eat within 3 days. Reheat in a skillet until steaming hot.",
    substitutions: [
      "Corn can replace the peas.",
      "Leave out the eggs for an egg-free version and add a drained can of beans for substance.",
      "Tamari can replace soy sauce.",
    ],
    season: "Anytime favorite",
  },
  {
    slug: "mushroom-stroganoff",
    title: "Mushroom Stroganoff",
    category: "Vegetarian",
    prepMinutes: 10,
    cookMinutes: 20,
    time: 30,
    servings: 4,
    difficulty: "Easy",
    tag: "Comfort food",
    image: img("photo-1504674900247-0877df9cc836"),
    imageAlt: "A bowl of mushroom stroganoff over egg noodles",
    description:
      "Mushrooms in a sour-cream paprika sauce served over egg noodles.",
    intro:
      "Give the mushrooms enough room to brown before you add liquid. Sour cream goes in off the boil so the sauce stays smooth. Egg noodles are the usual base, but any wide noodle works.",
    keywords: ["mushroom stroganoff recipe", "easy vegetarian stroganoff", "30 minute meatless pasta"],
    ingredients: [
      "12 oz egg noodles",
      "2 tbsp butter or olive oil",
      "1 onion, sliced",
      "1 lb mushrooms, sliced",
      "2 cloves garlic, minced",
      "1 tbsp paprika",
      "1 tbsp all-purpose flour",
      "1 1/2 cups low-sodium vegetable broth",
      "1/2 cup sour cream",
      "1 tbsp Dijon mustard",
      "Salt and black pepper",
      "Chopped parsley",
    ],
    steps: [
      "Cook the noodles in salted water until tender. Drain them.",
      "Heat the butter in a large skillet over medium-high heat. Cook the onion and mushrooms for 8 minutes, until the mushrooms are browned.",
      "Add the garlic and paprika for 30 seconds. Sprinkle on the flour and stir for 1 minute.",
      "Pour in the broth and simmer for 4 minutes, until slightly thick.",
      "Take the pan off the heat. Stir in the sour cream and Dijon. Season with salt and pepper.",
      "Serve over the noodles with parsley.",
    ],
    tips: "Do not boil the sauce after the sour cream is added or it can curdle.",
    storage:
      "Refrigerate sauce and noodles for up to 3 days. Reheat the sauce gently and loosen it with a splash of broth. Warm the noodles separately.",
    substitutions: [
      "Greek yogurt can replace sour cream if you stir it in off the heat.",
      "Wide pasta can replace egg noodles.",
      "A gluten-free flour blend can replace the all-purpose flour for thickening.",
    ],
    season: "Cozy classic",
  },
  {
    slug: "sweet-potato-black-bean-bowls",
    title: "Sweet Potato and Black Bean Bowls",
    category: "Vegetarian",
    prepMinutes: 10,
    cookMinutes: 30,
    time: 40,
    servings: 4,
    difficulty: "Easy",
    tag: "Bowl dinner",
    image: img("photo-1512621776951-a57141f2eefd"),
    imageAlt: "A bowl of roasted sweet potato, black beans, and greens",
    description:
      "Roasted sweet potato cubes, seasoned black beans, and rice with lime and yogurt.",
    intro:
      "Roast the sweet potatoes while the rice cooks and the beans warm. The bowl needs something cool and acidic at the end, which is why the lime and yogurt are not optional garnish.",
    keywords: ["sweet potato black bean bowl", "easy vegetarian dinner", "meatless dinner bowl"],
    ingredients: [
      "2 medium sweet potatoes, cubed",
      "1 tbsp olive oil",
      "1/2 tsp salt",
      "1/2 tsp chili powder",
      "1 can (15 oz) black beans, rinsed",
      "1/2 tsp ground cumin",
      "3 cups cooked rice",
      "2 cups chopped romaine or spinach",
      "1/2 cup plain yogurt",
      "1 lime, juiced",
    ],
    steps: [
      "Heat the oven to 425°F (220°C). Toss the sweet potatoes with oil, salt, and chili powder.",
      "Roast on a sheet pan for 25 to 30 minutes, stirring once, until tender and browned.",
      "Warm the beans with the cumin and a pinch of salt in a small saucepan.",
      "Stir the lime juice into the yogurt.",
      "Build bowls with rice, greens, sweet potatoes, and beans. Spoon the yogurt sauce over the top.",
    ],
    tips: "Cut the sweet potatoes smaller than 1 inch so they roast in the same window as the rice.",
    storage:
      "Refrigerate the components for up to 4 days. Keep the yogurt sauce separate. Reheat the sweet potatoes and beans, then add cold greens and sauce.",
    substitutions: [
      "Quinoa can replace the rice.",
      "Sour cream can replace the yogurt.",
      "A drained can of corn can be warmed with the beans.",
    ],
    season: "Fall favorite",
  },
  {
    slug: "spinach-ricotta-pasta",
    title: "Spinach Ricotta Pasta",
    category: "Vegetarian",
    prepMinutes: 10,
    cookMinutes: 15,
    time: 25,
    servings: 4,
    difficulty: "Easy",
    tag: "One-pot wonder",
    image: img("photo-1495214783159-3503fd1b572d"),
    imageAlt: "A bowl of pasta tossed with spinach and cheese",
    description:
      "Short pasta tossed with wilted spinach, ricotta, lemon, and Parmesan.",
    intro:
      "Ricotta makes a sauce when it meets hot pasta and a ladle of pasta water. It should look creamy, not dry or soupy. Lemon at the end keeps the cheese from tasting flat.",
    keywords: ["spinach ricotta pasta", "easy vegetarian pasta", "20 minute pasta dinner"],
    ingredients: [
      "12 oz short pasta",
      "1 tbsp olive oil",
      "2 cloves garlic, minced",
      "5 cups baby spinach",
      "1 cup whole-milk ricotta",
      "1/2 cup grated Parmesan",
      "1 lemon, zested and juiced",
      "1/2 tsp salt",
      "1/4 tsp black pepper",
    ],
    steps: [
      "Cook the pasta in salted water until al dente. Reserve 1 cup of pasta water and drain.",
      "In the empty pot, heat the oil over medium heat. Cook the garlic for 30 seconds.",
      "Add the spinach and stir until wilted.",
      "Return the pasta to the pot. Add the ricotta, Parmesan, lemon zest, salt, pepper, and about 1/2 cup of pasta water.",
      "Toss until creamy, adding more pasta water if needed. Finish with the lemon juice and serve.",
    ],
    tips: "Take the pot off the heat before you add the ricotta if it looks like it might boil. Boiling ricotta can turn grainy.",
    storage:
      "Refrigerate for up to 3 days. Reheat with a splash of water in a skillet over medium-low heat.",
    substitutions: [
      "Cottage cheese blended until smooth can replace the ricotta.",
      "Frozen spinach, thawed and squeezed dry, can replace fresh spinach. Use about 1 cup.",
    ],
    season: "Weeknight staple",
  },
];

export const categories = [
  {
    slug: "dinner",
    name: "Easy Dinners",
    desc: "Easy dinner recipes you can cook on a weeknight.",
    intro:
      "These dinners are built for a night when you still have to pack tomorrow's lunch. Most of them use one pan or one pot, and the chicken, pork, and turkey recipes include a temperature to check before you serve.",
    body:
      "Start with a sheet-pan chicken, a skillet pasta, or the beef and broccoli if you want dinner in about half an hour. The meal planner can turn a few of these into a grocery list so you are not deciding again at 6 p.m.",
    image: img("photo-1414235077428-338989a2e8c0"),
    imageAlt: "A family-style dinner set on a wooden table",
  },
  {
    slug: "breakfast",
    name: "Breakfast",
    desc: "Make-ahead breakfasts and slow weekend favorites.",
    intro:
      "Some of these breakfasts are meant to be baked or rolled once and eaten for several mornings. Others, like the pancakes, are better cooked when you have a slower start.",
    body:
      "Baked oatmeal, the frittata, overnight oats, and the breakfast burritos all keep in the refrigerator. Reheat egg dishes covered, and add a splash of milk to leftover oatmeal so it softens.",
    image: img("photo-1478144592103-25e218a04891"),
    imageAlt: "A breakfast table with fruit, toast, and coffee",
  },
  {
    slug: "soups",
    name: "Soups and Stews",
    desc: "Comforting bowls for chilly days and busy nights.",
    intro:
      "A pot of soup is one of the easier ways to cover more than one meal. These recipes use broth, canned tomatoes, beans, or cooked chicken so you are not watching a stockpot all afternoon.",
    body:
      "Cool soup in a wide container and refrigerate it within two hours. Noodles in the chicken soup keep absorbing broth, so store them separately when you can. The leftover guide explains how long a pot should stay in the refrigerator.",
    image: img("photo-1476224203421-9ac39bcb3327"),
    imageAlt: "A pot of vegetable soup on a stove",
  },
  {
    slug: "vegetarian",
    name: "Vegetarian",
    desc: "Colorful, satisfying meat-free meals for any day.",
    intro:
      "These meatless dinners rely on beans, eggs, cheese, or coconut milk so the plate is actually filling. They use the same kind of pantry list as the other weeknight recipes.",
    body:
      "Pair a bean skillet or curry with rice you already cooked, or use the fried rice when you have cold rice to use up. The vegetarian plate guide explains how to balance beans, a starch, and something fresh.",
    image: img("photo-1540189549336-e6e99c3679fe"),
    imageAlt: "A colorful vegetarian salad bowl with greens and vegetables",
  },
];

export function findRecipe(slug) {
  return recipes.find((recipe) => recipe.slug === slug);
}
